=== Raphhh/IKSchema/ik.xsd
<?xml version="1.0"?>
<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="https://github.com/Raphhh/IKSchema"
	xmlns="https://github.com/Raphhh/IKSchema"
	elementFormDefault="qualified">

	<xs:element name="ik">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="meta">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="version" type="xs:token" minOccurs="0" maxOccurs="1"/>
							<xs:element name="date" type="xs:date" minOccurs="0" maxOccurs="1"/>
							<xs:element name="reference" type="xs:anyURI" minOccurs="1" maxOccurs="1"/>
							<xs:element name="language" type="xs:language" minOccurs="1" maxOccurs="1"/>
							<xs:element name="title" type="xs:normalizedString" minOccurs="1" maxOccurs="1"/>
							<xs:element name="author" type="xs:normalizedString" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="description" type="xs:normalizedString" minOccurs="0" maxOccurs="1"/>
							<xs:element name="image" type="xs:anyURI" minOccurs="0" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element> 

</xs:schema>

=== Raphhh/IKSchema/tests/__fixtures__/metaAll.xml
<?xml version="1.0"?>
<ik
        xmlns="https://github.com/Raphhh/IKSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://github.com/Raphhh/ik/ik.xsd">
    <meta>
        <version>1.0.3</version>
        <date>2000-12-31</date>
        <reference>https://github.com/Raphhh/ik</reference>
        <language>en-GB</language>
        <title>title value</title>
        <author>author 1</author>
        <author>author 2</author>
        <description>description of the ik</description>
        <image uri="https://github.com/Raphhh/ik/image.png">legend</image>
    </meta>
    <glossary></glossary>
    <taxons></taxons>
</ik>
